# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fabianjv.github.io
title: Professional Profile
email: fabianjimenezv01@gmail.com
author: Fabian Jiménez Vásquez
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: instagram
    url: 
